# The URL the site will be built for
base_url = "https://ahmetilten.com"

theme = "terminimal"

# Sass compilation is required
compile_sass = true

# The theme supports feeds (RSS and ATOM)
generate_feed = true

# Use `rss.xml` for RSS feeds and `atom.xml` for ATOM
feed_filename = "atom.xml"

# Optional: enable tags
# taxonomies = [
#	{name = "tags"}
#]

# Code highlighting
[markdown]
highlight_code = true

[extra]
# One of: blue, green, orange, pink, red.
# Defaults to blue.
# Append -light for light themes, e.g. blue-light
# Or append -auto, e.g. blue-auto
# accent_color = "blue"
accent_color = "orange"

# One of: blue, dark, green, orange, pink, red, light, auto
# Enabling dark background will also modify primary font color to be darker.
# Defaults to accent color (or, if not accent color specified, to blue).
background_color = ""

# The logo text - defaults to "Terminimal theme"
logo_text = "Ahmet İlten"

# The logo link - defaults to base_url.
#logo_home_link = "/take/me/away!"

# Author name: when specified, modifies the default
# copyright text. Apart from author, it will
# contain current year and a link to the theme.
author = "Ahmet İlten"

# Copyright text in HTML format. If specified,
# entirely replaces default copyright and author.
#copyright_html = "My custom&nbsp;<b>copyright</b>"

# menu is enabled by adding menu_items (optional)
menu_items = [
	# each of these is optional, name and url are required
	# $BASE_URL is going to be substituted by base_url from configuration
	{name = "about me", url = "$BASE_URL/about-me"},

	# tags should only be enabled if you have "tags" taxonomy
	# see documentation below for more details
	{name = "portfolio", url = "$BASE_URL/portfolio"},
	{name = "blog", url = "$BASE_URL/blog"},

	# set newtab to true to make the link open in new tab
	{name = "github", url = "https://www.github.com/iltenahmet", newtab = true},
	{name = "youtube", url = "https://www.youtube.com/@iltenahmet", newtab = true},
	{name = "linkedin", url = "https://www.linkedin.com/in/iltenahmet", newtab = true},
	{name = "steam", url = "https://store.steampowered.com/search/?developer=Ahmet%20Ilten", newtab = true},

	# {name = "resume", url = "$BASE_URL/ahmet-ilten-resume.pdf"},
]

# Whether to show links to earlier and later (aka. higher/lower) posts
# on each post page (defaults to true).
enable_post_view_navigation = true

# The text shown at the bottom of a post,
# before earlier/later post links.
# Defaults to "Thanks for reading! Read other posts?"
post_view_navigation_prompt = "Check out other stuff?"

# Use full Hack character set, not just a subset.
# Switch this to true if you need full unicode support.
# Defaults to false.
use_full_hack_font = true 

# Optional: Global favicon URL and mimetype.
#           Mimetype defaults to "image/x-icon".
#           The URL should point at a file located
#           in your site's "static" directory.
# favicon = "/favicon.png"
# favicon_mimetype = "image/png"

# Optional: Set how <title> elements are rendered.
# Values:
# - "main_only" -- only the main title (`config.title`) is rendered.
# - "page_only" -- only the page title (if defined) is rendered,
#                  falling back to `config.title` if not defined or empty.
# - "combined" -- combine like so: "page_title | main_title",
#                 or if page_title is not defined or empty, fall back to `main_title`
#
# Note that the main (index) page only has the main title.
page_titles = "combined"

# Optional: default image to use for OpenGraph.
#           If the page doesnt set og_image, use this one as fallback. Usefull
#           for indexes and taxonomies' pages.
#default_og_image = "static/ocean.jpg"
